import type { Metadata } from "next";
import localFont from "next/font/local"
import "./globals.css";
import Header from "../components/layout/header";


const Sageffine = localFont({
  src: [
    {
      path: "../assets/fonts/sageffine-cdnfonts/Sageffine-BF654db192d17bd.otf",
      weight: "400",
      style: "normal"
    }
  ],
  variable: "--font-sageffine",
  display: "swap"
})

const Akkurat = localFont({
  src: [
    {
      path: "../assets/fonts/AkkuratPro/Akkurat Pro.ttf",
      weight: "400",
      style: "regular"
    }
  ],
  variable: "--font-akkurat",
  display: "swap"
})

export const metadata: Metadata = {
  title: "Despi: Destiny Control",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${Akkurat.variable} ${Sageffine.variable} antialiased`}
      >
        <Header/>
        <main className="pt-20">{children}</main>
      </body>
    </html>
  );
}
